### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Rickert41** [StanBankras/functional-programming#1]
Goede onderzoeksvraag en sub-vragen!
Misschien kan je de data die je gaat gebruiken ook in de readme zetten, in plaats van alleen in de wiki. Het is niet heel veel tekst en voegt wel veel informatie toe aan de readme. Wat je misschien ook kan doen is de datasets in je readme vermelden, en de velden die je gebruikt uit die datasets in de wiki.
Verder ook al een goede beschrijving van hoe je dit project zelf installeert en runt, en je wiki ziet er ook echt super uitgebreid uit, nice!

**Comment by StanBankras** [comment]
Thanks! In mijn frontend-data repository pas ik de tip toe om data zo veel mogelijk ook al in mijn readme te linken.
