### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by didiercatz** [StanBankras/functional-programming#2]
## Project structure

- Great work on having seperate files for each 'type' of function.
- The ES6 modules seem to work nicely.
- You could try placing your `js` files in a dedicated directory, such as `src`, so not to clutter your root directory.

## Concept & Debrief
_I won't mention anything that has already been mentioned in other issues._
- Your README has a heading called 'Suquestions'; however, only one sub question is present. I would suggest changing the copy or adding more sub questions. Nice job on the assumptions.
- You could translate the quote by Xander van Uffelen for international readers.
- Great job on your wiki's Process page!

**Comment by StanBankras** [comment]
### Project structure
- I have improved the project structure, you were absolutely right about it looking a bit cluttered. Thanks!

### Concept & Debrief
- I think you misread the subquestions, there are actually more than one subquestion;
- I have translated the quote by Xander, it makes sense as my whole project is in English;
